### ISSUE TITLE
AduDatePicker属性建议优化或者添加注释

### ISSUE THREAD

**Issue by yinghualuowu** [aduskin/AduSkin#1]
当我使用AduDatePicker时，不得不梳理清楚里面对应的属性。
以下面代码为例
```
<metro:AduDatePicker x:Name="StartDate"
                             HorizontalAlignment="Left" 
                             Margin="0 4 4 4" Width="150" 
                             VerticalAlignment="Center" 
                             Height="28"
                             Type="DateTime" 
                             CornerRadius="3" 
                             DateStringFormat="yyyy/MM/dd"/>
```
如果我需要展示时间 StartDate.DisplayDate = System.DateTime.Now;显示为空，使用SelectedDate显示正常。（看命名感觉应该是第一个属性有效）
当我选择时间时
![image](https://user-images.githubusercontent.com/22371568/71511783-7f292b80-28ce-11ea-9cea-1c093eb2886b.png)
StartDate里面的数据为：

  | 名称 | 值 | 类型
-- | -- | -- | --
▶ | SelectedDate | {2019/12/31 0:00:00} | System.DateTime?
▶ | SelectedTime | {2019/12/27 20:35:07} | System.DateTime?
▶ | DisplayDate | {2019/12/31 0:00:00} | System.DateTime

没办法直接拉取选择的时间。只能通过上面几个数据的拼接。
```
public static DateTime? GetSelectDateTime(this AduDatePicker picker)
{
    DateTime? result;
    if (picker.SelectedDate != null && picker.SelectedTime != null)
    {
        result = new DateTime(picker.SelectedDate.Value.Year,
            picker.SelectedDate.Value.Month,
            picker.SelectedDate.Value.Day,
            picker.SelectedTime.Value.Hour,
            picker.SelectedTime.Value.Minute,
            picker.SelectedTime.Value.Second);
    }
    else
    {
        result = null;
    }
    return result;
}
```
另外当清空时间时，我以为获取到的数据应该是null，结果并不是。（当然这是个体验问题）

**Comment by aduskin** [comment]
ok，谢谢你的反馈，这边调试查看确实有此bug，我会抽空修复该问题

**Comment by aduskin** [comment]
你好，你的问题已修复，现在可以通过“SelectedDateTime“来获取和设置当前选择的日期和时间

SelectedDate：是指选择的日期(不含时分秒)，针对日历控件使用
SelectedTime：是指选择的时间(不含时间)，针对时间选择器使用
DisplayDate：显示的日期(无时间部分)
默认所有属性都是DateTime类型(含日期和时间)，因DatePicker为组合控件，在DatePicker中尽量不使用SelectedTime，该属性仅对TimeSelector控件使用。

**Comment by yinghualuowu** [comment]
好哒，谢谢大佬~

**Comment by yinghualuowu** [comment]
大佬什么时候可以把nuget包更新一下呢>W<

**Comment by aduskin** [comment]
已经发布新版本了 Version1.1.1.4
