### ISSUE TITLE
使用AduDatePicker选择时间出现错误

### ISSUE THREAD

**Issue by AmamiyaYuko07** [aduskin/AduSkin#17]
使用AduDatePicker控件时，我绑定了SelectedDateTime这个属性，但是选择的是下午两点，前台也显示的是14:00:00，但是传到后台之后就变成了02:00:00，我应该是使用的最新版本

**Comment by yinghualuowu** [comment]
因为逻辑是获取12小时制哦，所以14点变为了2点。不知道是设计如此还是落下了

**Comment by AmamiyaYuko07** [comment]
> 因为逻辑是获取12小时制哦，所以14点变为了2点。
> [这个提交已经修复了问题](https://github.com/aduskin/AduSkin/commit/a95f8d4cf77118b5b3134f25d001fcde12c79f0d)
> 你再试一试吧

我需要重新安装吗？ nuget上使用的1.1.1.8版本已经是最新版了哦。

**Comment by AmamiyaYuko07** [comment]
已解决  我直接从源代码拉下来生成了一个dll，感谢
