### ISSUE TITLE
Readme 中的协议和License描述不符

### ISSUE THREAD

**Issue by prime167** [aduskin/AduSkin#27]
首先感谢您的辛苦付出，开源这么好的软件。

Readme中是LGPL，License是GPL。前者用中文说的很清楚，不修改源代码可以商用，看修改时间，先添加的license，后在readme中添加LGPL的描述，那实际的协议就是LGPL？请修改License文件内容，使二者统一，也更利用推广。谢谢！

**Comment by liupeiqiHN** [comment]
确实，希望作者统一License内容，避免误解混淆，明确是GPL还是LGPL。
