### ISSUE TITLE
日期选择添加清空功能

### ISSUE THREAD

**Issue by yinghualuowu** [aduskin/AduSkin#4]
- 为什么要有这个功能？
- 因为有时候我们不需要带有时间这个条件，一旦选中时间后，则无法清空选择时间。QAQ。
- 具体一点。。>W<
- 以demo为例，Type默认的情况下，下方显示清空按钮就好了。截图为个人的魔改版本
![image](https://user-images.githubusercontent.com/22371568/73515868-afb23700-4431-11ea-82a1-295c68a9a39a.png)
- 另外报个bug，这个清空按钮对AduDatePicker.SelectedDate无效，貌似只是清空了PART_Calendar.SelectedDate。所以就算是目前的清空，拿到的日期还是不变的。

**Comment by aduskin** [comment]
ok，我看到了以前版本的清空方式，仅仅对日历控件的数据进行清空，未对当前AduDataPicker的数据进行清空，现在已经加入了清空日期和时间
